server.address=0.0.0.0
server.forward-headers-strategy=framework
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

spring.h2.console.enabled=false
spring.datasource.hikari.maximum-pool-size=10

management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
