spring.datasource.url=${INTENT_TRACE_DATABASE_URL}
spring.datasource.username=${INTENT_TRACE_DATABASE_USERNAME}
spring.datasource.password=${INTENT_TRACE_DATABASE_PASSWORD}
spring.h2.console.enabled=false
